---
- name: Generate Reports for AWS VPCs
  hosts: localhost
  gather_facts: yes
  vars:
    ec2_regions:
       - "us-east-1"          # N Virginia
       - "us-east-2"          # Ohio
       - "us-west-1"          # N Cali
       - "us-west-2"          # Oregon
       - "ap-northeast-1"     # Tokyo
       - "ap-southeast-1"     # Singapore
       - "ap-south-1"         # Mumbai
       - "ca-central-1"       # Canada
       - "eu-central-1"       # Frankfurt
       - "eu-west-1"          # Ireland
       - "eu-west-2"          # London
    debug_teardown: false
    attendance: true

  tasks:
    - include_tasks: tasks/nuke/tasks.yml
      with_items: "{{ ec2_regions }}"
      loop_control:
        loop_var: ec2_region
