---
- name: Generate Reports for AWS VPCs
  hosts: localhost
  gather_facts: no
  vars:
    ec2_regions:
       - "us-east-1"          # N Virginia
       - "us-east-2"          # Ohio
       - "us-west-1"          # N Cali
       - "us-west-2"          # Oregon
       - "ap-northeast-1"     # Tokyo
       - "ap-southeast-1"     # Singapore
       - "ap-south-1"         # Mumbai
       - "ca-central-1"       # Canada
       - "eu-central-1"       # Frankfurt
       - "eu-west-1"          # Ireland
       - "eu-west-2"          # London

  tasks:
  - block:
    - name: "{{ ec2_region }} - Remove the fragments directory to clean it out"
      file:
         state: absent
         path: "{{ playbook_dir }}/reports/fragments-vpcs/"

    - name: "{{ ec2_region }} - Recreate the fragments directory"
      file:
         state: directory
         path: "{{ playbook_dir }}/reports/fragments-vpcs/"

    - include_tasks: tasks/route53/vpcs.yml
      with_items: "{{ ec2_regions }}"
      loop_control:
        loop_var: ec2_region

    - name: "{{ ec2_region }} - Concat all the csv files"
      assemble: 
        src: "{{ playbook_dir }}/reports/fragments-vpcs//"
        dest: "{{ playbook_dir }}/reports/vpcs.txt"
      run_once: true 
#    when: false

  - include_tasks: tasks/route53/routes.yml
